### ISSUE TITLE
posible nombre incorrecto de atributo

### ISSUE THREAD

**Issue by om24-fi** [FIUNER-LICA/ayed-tps-codigos-iniciales-para-estudiantes#14]
https://github.com/FIUNER-LICA/ayed-tps-codigos-iniciales-para-estudiantes/blob/2c8d1d39b965fad2d427bd9ccbdba0539aa34158/TP1_juego_guerra/pruebas/test_mazo.py#L23C53-L23C57

Estuve en clase de consulta el viernes con Jordán y vimos que en esta linea de codigo llama la clase mazo a un atributo mazo, se sugiere por Jordán corregir cambiar el nombre del atributo mazo por cartas.

**Comment by dzjavier** [comment]
Hola om24-fi,
De acuerdo, lo vamos viendo con el equipo.
Saludos,
Javier

**Comment by dzjavier** [comment]
@fmasamaniego por favor, mira el caso mencionado, para mejorar el test. Cualquier cosa, consultalo con @jordaninsfran o conmigo.
Saludos,
Javier

**Comment by dzjavier** [comment]
Hola Francisco. 
Avancemos lo conversado. Cambio de nombre de atributos y acceso solo a miembros públicos. Es decir, modifiquemos el test para representar mejor el comportamiento del mazo y no tanto su implementación de con lista doblemente enlazada.

**Comment by fmasamaniego** [comment]
Hola Javier.
Ya está implementado lo pedido, ahora el test solo se centra en el mazo, sin acceder a los atributos de la LDE, además se corrigió el código de la clase Mazo para agregarle la privacidad correspondiente.
